# Generated by Django 5.2.12 on 2026-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='money',
            new_name='balance',
        ),
    ]
