# Generated by Django 5.2.11 on 2026-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_crew",
            field=models.BooleanField(default=False),
        ),
    ]
