# Generated by Django 5.2.12 on 2026-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='journey',
            name='first_class_multiplier',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
        ),
        migrations.AddField(
            model_name='journey',
            name='second_class_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('first_class', 'First Class'), ('second_class', 'Second Class'), ('economy', 'Economy')], default='second_class'),
        ),
    ]
