# Generated by Django 5.2.12 on 2026-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_journey_base_price_journey_first_class_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='places_in_cargo',
        ),
        migrations.AddField(
            model_name='routestation',
            name='break_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='economy_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='first_class_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='second_class_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traintype',
            name='average_speed',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
