# Generated by Django 5.2.12 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_remove_train_places_in_cargo_routestation_break_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='platform',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('delay', 'Delay'), ('cancellation', 'Cancellation'), ('platform_change', 'Platform change'), ('general', 'General')], default='general', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('bought', 'Bought'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending'),
        ),
    ]
